apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: happy-paisa-app
  namespace: "155452960053"
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 537.0.0
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: "155452960053-compute@developer.gserviceaccount.com"
      containers:
      - name: happy-paisa-app-1
        image: nginx:alpine
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
  traffic:
  - percent: 100
    latestRevision: true